source :rubygems
gem "MINT-scxml", :git => "ssh://git@multi-access.de/scxml.git", :branch => "master"
gem "MINT-statemachine",  :git => "ssh://git@multi-access.de/statemachine.git", :branch => "master"
gem "MINT-core", :git => "ssh://git@multi-access.de/MINT-core.git", :branch => "master"
gem "rspec", "1.3.1"
gem "dm-core","0.10.2"
gem "dm-rinda-adapter" ,  :git => "ssh://git@multi-access.de/dm-rinda-adapter.git", :branch => "master"
gem "rake","0.9.2"
gem "dm-types","0.10.2"
gem "wxruby","2.0.0"
gem "rmagick","2.13.1"
gem "eventmachine", "0.12.10"
gem "hoe", "2.9.6"
